### ISSUE TITLE
Chat screen Display issue

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/intulse-app-beta#23] opened 2020-09-23 13:54 UTC
**Describe the bug [required]**
Chat screen on Mobile app for IOS not displaying correctly

**To Reproduce [required]**
1. Go to Intulse app on IOS
2. impersonate Sean Higurea from 56596 - Endeavor Financial Advisors
3. Go to Chat screen
4. Select Chat conversation

**Expected behavior [required]**
Conversation is displayed properly

**Actual behavior [required]**
converstaion is overlapped and not displaying properly

**Screenshots**
![IMG_9559](https://user-images.githubusercontent.com/57546882/94021826-73499780-fd82-11ea-8083-35bea584c773.PNG)

**Desktop (please complete the following information):**
 - OS: IOS

**Smartphone (please complete the following information):**
 - Device: Iphone 7+

**Comment by darrenhollick** [comment] 2020-09-23 20:38
duplicate of #22

**Closed by darrenhollick** 2020-09-23 20:38 UTC
Labels: bug, duplicate
